apiVersion: "apps/v1"
kind: Deployment
metadata:
  name: webapp-deployment
  namespace: web
  labels:
    app: webapp
spec:
  selector:
    matchLabels:
      app: webapp
  template:
    metadata: 
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: <MY-REGISTRY>.azurecr.io/webapp
        ports:
        - containerPort: 80
